POPULAR_TOKEN_NAMES = {
    "Bitcoin": ["bitcoin", "btc"],
    "Ethereum": ["eth", "ethereum"],
    "Tether": ["tether", "usdt"],
    "XRP": ["ripple", "xrp"],
    "BNB": ["binancecoin", "bnb"],
    "USDC": ["usd coin", "usd-coin", "usdc", "usdcoin"],
    "Solana": ["sol", "solana"],
    "TRON": ["tron", "trx"],
    "Figure Heloc": [
        "figr heloc",
        "figr-heloc",
        "figrheloc",
        "figure heloc",
        "figure-heloc",
        "figureheloc",
    ],
    "Hyperliquid": ["hype", "hyperliquid"],
    "Dogecoin": ["doge", "dogecoin"],
    "Zcash": ["zcash", "zec"],
    "Rain": ["rain"],
    "USDS": ["usds"],
    "LEO Token": ["leo", "leo token", "leo-token", "leotoken"],
    "Chainlink": ["chainlink", "link"],
    "Cardano": ["ada", "cardano"],
    "WhiteBIT Coin": [
        "wbt",
        "whitebit",
        "whitebit coin",
        "whitebit-coin",
        "whitebitcoin",
    ],
    "Monero": ["monero", "xmr"],
    "Stellar": ["stellar", "xlm"],
    "Bitcoin Cash": ["bch", "bitcoin cash", "bitcoin-cash", "bitcoincash"],
    "Canton": ["canton", "canton network", "canton-network", "cantonnetwork"],
    "Dai": ["dai"],
    "Gram (prev. Toncoin)": [
        "gram",
        "gram prev toncoin",
        "gram-prev-toncoin",
        "gramprevtoncoin",
        "the open network",
        "the-open-network",
        "theopennetwork",
    ],
    "Ethena USDe": ["ethena usde", "ethena-usde", "ethenausde", "usde"],
    "Litecoin": ["litecoin", "ltc"],
    "USD1": ["usd1", "usd1 wlfi", "usd1-wlfi", "usd1wlfi"],
    "Hedera": [
        "hbar",
        "hedera",
        "hedera hashgraph",
        "hedera-hashgraph",
        "hederahashgraph",
    ],
    "Global Dollar": ["global dollar", "global-dollar", "globaldollar", "usdg"],
    "Sui": ["sui"],
    "Avalanche": ["avalanche", "avalanche 2", "avalanche-2", "avalanche2", "avax"],
    "Shiba Inu": ["shib", "shiba inu", "shiba-inu", "shibainu"],
    "Circle USYC": [
        "circle usyc",
        "circle-usyc",
        "circleusyc",
        "hashnote usyc",
        "hashnote-usyc",
        "hashnoteusyc",
        "usyc",
    ],
    "PayPal USD": ["paypal usd", "paypal-usd", "paypalusd", "pyusd"],
    "Uniswap": ["uni", "uniswap"],
    "Cronos": [
        "cro",
        "cronos",
        "crypto com chain",
        "crypto-com-chain",
        "cryptocomchain",
    ],
    "Tether Gold": ["tether gold", "tether-gold", "tethergold", "xaut"],
    "BlackRock USD Institutional Digital Liquidity Fund": [
        "blackrock usd institutional digital liquidity fund",
        "blackrock-usd-institutional-digital-liquidity-fund",
        "blackrockusdinstitutionaldigitalliquidityfund",
        "buidl",
    ],
    # TODO
    # "NEAR Protocol": ["near", "near protocol", "near-protocol", "nearprotocol"],
    "MemeCore": ["memecore"],
    "OKB": ["okb"],
    "Bittensor": ["bittensor", "tao"],
    "Ondo US Dollar Yield": [
        "ondo us dollar yield",
        "ondo-us-dollar-yield",
        "ondousdollaryield",
        "usdy",
    ],
    "Aave": ["aave"],
    "Ripple USD": ["ripple usd", "ripple-usd", "rippleusd", "rlusd"],
    "Pump.fun": ["pump", "pump fun", "pump-fun", "pumpfun"],
    "PAX Gold": ["pax gold", "pax-gold", "paxg", "paxgold"],
    "World Liberty Financial": [
        "wlfi",
        "world liberty financial",
        "world-liberty-financial",
        "worldlibertyfinancial",
    ],
    "Ondo": ["ondo", "ondo finance", "ondo-finance", "ondofinance"],
    "Aster": ["aster", "aster 2", "aster-2", "aster2"],
    "Pepe": ["pepe"],
    "Ethena": ["ena", "ethena"],
    "Morpho": ["morpho"],
    "Mantle": ["mantle", "mnt"],
    "Sky": ["sky"],
    "Polkadot": ["dot", "polkadot"],
    "HTX DAO": ["htx", "htx dao", "htx-dao", "htxdao"],
    "USDD": ["usdd"],
    "Worldcoin": ["wld", "worldcoin", "worldcoin wld", "worldcoin-wld", "worldcoinwld"],
    "Internet Computer": [
        "icp",
        "internet computer",
        "internet-computer",
        "internetcomputer",
    ],
    "Bitget Token": ["bgb", "bitget token", "bitget-token", "bitgettoken"],
    "Falcon USD": [
        "falcon finance",
        "falcon usd",
        "falcon-finance",
        "falcon-usd",
        "falconfinance",
        "falconusd",
        "usdf",
    ],
    "BFUSD": ["bfusd"],
    "United Stables": ["united stables", "united-stables", "unitedstables"],
    "Ethereum Classic": [
        "etc",
        "ethereum classic",
        "ethereum-classic",
        "ethereumclassic",
    ],
    "Spiko Amundi Overnight Swap Fund (EUR)": [
        "eursafo",
        "spiko amundi overnight swap fund eur",
        "spiko-amundi-overnight-swap-fund-eur",
        "spikoamundiovernightswapfundeur",
    ],
    "USDGO": ["usdgo"],
    "POL (ex-MATIC)": [
        # "pol", # TODO: mention somewhere that this manually removed
        "pol ex matic",
        "pol-ex-matic",
        "polexmatic",
        "polygon ecosystem token",
        "polygon-ecosystem-token",
        "polygonecosystemtoken",
    ],
    "Bitway": ["bitway", "btw"],
    "KuCoin": ["kcs", "kucoin", "kucoin shares", "kucoin-shares", "kucoinshares"],
    "Pi Network": ["pi network", "pi-network", "pinetwork"],
    "Blockchain Capital": [
        "bcap",
        "blockchain capital",
        "blockchain-capital",
        "blockchaincapital",
    ],
    "Spiko EU T-Bills Money Market Fund": [
        "eutbl",
        "spiko eu t bills money market fund",
        "spiko-eu-t-bills-money-market-fund",
        "spikoeutbillsmoneymarketfund",
    ],
    "Quant": ["qnt", "quant", "quant network", "quant-network", "quantnetwork"],
    "Janus Henderson Anemoy Treasury Fund": [
        "janus henderson anemoy treasury fund",
        "janus-henderson-anemoy-treasury-fund",
        "janushendersonanemoytreasuryfund",
        "jtrsy",
    ],
    "JUST": ["jst", "just"],
    "Cosmos Hub": ["atom", "cosmos", "cosmos hub", "cosmos-hub", "cosmoshub"],
    "Algorand": ["algo", "algorand"],
    "Lighter": ["lighter", "lit"],
    "Gate": ["gate", "gatechain token", "gatechain-token", "gatechaintoken"],
    "Venice Token": ["venice token", "venice-token", "venicetoken", "vvv"],
    "NEXO": ["nexo"],
    "Invesco Short Duration US Government Securities Fund": [
        "invesco short duration us government securities fund",
        "invesco-short-duration-us-government-securities-fund",
        "invescoshortdurationusgovernmentsecuritiesfund",
        "superstate short duration us government securities fund ustb",
        "superstate-short-duration-us-government-securities-fund-ustb",
        "superstateshortdurationusgovernmentsecuritiesfundustb",
        "ustb",
    ],
    "Kaspa": ["kas", "kaspa"],
    # TODO: add remark manual removal
    # "\u200b\u200bStable": ["stable", "stable 2", "stable-2", "stable2"],
    "Render": ["render", "render token", "render-token", "rendertoken"],
    "Janus Henderson Anemoy AAA CLO Fund": [
        "jaaa",
        "janus henderson anemoy aaa clo fund",
        "janus-henderson-anemoy-aaa-clo-fund",
        "janushendersonanemoyaaaclofund",
    ],
    "Jupiter": [
        "jup",
        "jupiter",
        "jupiter exchange solana",
        "jupiter-exchange-solana",
        "jupiterexchangesolana",
    ],
    "GHO": ["gho"],
    "Arbitrum": ["arb", "arbitrum"],
    "YLDS": ["ylds"],
    "Official Trump": ["official trump", "official-trump", "officialtrump", "trump"],
    "Beldex": ["bdx", "beldex"],
    "Filecoin": ["fil", "filecoin"],
    "Ether.fi": ["ether fi", "ether-fi", "etherfi", "ethfi"],
    "Flare": ["flare", "flare networks", "flare-networks", "flarenetworks", "flr"],
    "XDC Network": [
        "xdc",
        "xdc network",
        "xdc-network",
        "xdce crowd sale",
        "xdce-crowd-sale",
        "xdcecrowdsale",
        "xdcnetwork",
    ],
    "PancakeSwap": [
        "cake",
        "pancakeswap",
        "pancakeswap token",
        "pancakeswap-token",
        "pancakeswaptoken",
    ],
    "Aptos": ["apt", "aptos"],
    "Usual USD": ["usd0", "usual usd", "usual-usd", "usualusd"],
    "Dash": ["dash"],
    "Pudgy Penguins": ["pengu", "pudgy penguins", "pudgy-penguins", "pudgypenguins"],
    "Curve DAO": [
        "crv",
        "curve dao",
        "curve dao token",
        "curve-dao",
        "curve-dao-token",
        "curvedao",
        "curvedaotoken",
    ],
    "Injective": [
        "inj",
        "injective",
        "injective protocol",
        "injective-protocol",
        "injectiveprotocol",
    ],
    "币安人生 (BinanceLife)": ["bianrensheng", "binancelife"],
    "VeChain": ["vechain", "vet"],
    "TrueUSD": ["true usd", "true-usd", "trueusd", "tusd"],
    "A7A5": ["a7a5"],
    "Provenance Blockchain": [
        "hash",
        "hash 2",
        "hash-2",
        "hash2",
        "provenance blockchain",
        "provenance-blockchain",
        "provenanceblockchain",
    ],
    "Virtuals Protocol": [
        "virtual",
        "virtual protocol",
        "virtual-protocol",
        "virtualprotocol",
        "virtuals protocol",
        "virtuals-protocol",
        "virtualsprotocol",
    ],
    "Aerodrome Finance": [
        "aero",
        "aerodrome finance",
        "aerodrome-finance",
        "aerodromefinance",
    ],
    "EURC": ["eurc", "euro coin", "euro-coin", "eurocoin"],
    "Stacks": ["blockstack", "stacks", "stx"],
    "LayerZero": ["layerzero", "zro"],
    "SPX6900": ["spx", "spx6900"],
    "Pyth Network": ["pyth", "pyth network", "pyth-network", "pythnetwork"],
    "USX": ["usx"],
    "Artificial Superintelligence Alliance": [
        "artificial superintelligence alliance",
        "artificial-superintelligence-alliance",
        "artificialsuperintelligencealliance",
        "fet",
        "fetch ai",
        "fetch-ai",
        "fetchai",
    ],
    "Celestia": ["celestia", "tia"],
    "Ondo Short-Term U.S. Government Bond Fund": [
        "ondo short term u s government bond fund",
        "ondo-short-term-u-s-government-bond-fund",
        "ondoshorttermusgovernmentbondfund",
        "ousg",
    ],
    "Kinesis Gold": ["kau", "kinesis gold", "kinesis-gold", "kinesisgold"],
    "Monad": ["mon", "monad"],
    "First Digital USD": [
        "fdusd",
        "first digital usd",
        "first-digital-usd",
        "firstdigitalusd",
    ],
    "Midnight": ["midnight", "midnight 3", "midnight-3", "midnight3", "night"],
    "Bitcoin SV": [
        "bitcoin cash sv",
        "bitcoin sv",
        "bitcoin-cash-sv",
        "bitcoin-sv",
        "bitcoincashsv",
        "bitcoinsv",
        "bsv",
    ],
    "Sun Token": ["sun", "sun token", "sun-token", "suntoken"],
    "Lido DAO": ["ldo", "lido dao", "lido-dao", "lidodao"],
    "Pendle": ["pendle"],
    "Gnosis": ["gno", "gnosis"],
    "Sei": ["sei", "sei network", "sei-network", "seinetwork"],
    "Velvet": ["velvet"],
    "apxUSD": ["apxusd"],
    "SoFiUSD": ["sofid", "sofiusd"],
    "Terra Luna Classic": [
        "lunc",
        "terra luna",
        "terra luna classic",
        "terra-luna",
        "terra-luna-classic",
        "terraluna",
        "terralunaclassic",
    ],
    "Jito": [
        "jito",
        "jito governance token",
        "jito-governance-token",
        "jitogovernancetoken",
        "jto",
    ],
    "Unibase": ["unibase"],
    "BitTorrent": ["bittorrent", "btt"],
    "Bonk": ["bonk"],
    "USDtb": ["usdtb"],
    "Plasma": ["plasma", "xpl"],
    "Olympus": ["ohm", "olympus"],
    "crvUSD": ["crvusd"],
    "RealLink": ["real", "reallink"],
    "AINFT": ["ainft", "apenft", "nft"],
    "OnRe Tokenized Reinsurance": [
        "onre tokenized reinsurance",
        "onre-tokenized-reinsurance",
        "onretokenizedreinsurance",
        "onyc",
    ],
    "Falcon Finance": ["falcon finance ff", "falcon-finance-ff", "falconfinanceff"],
    "Kite": ["kite", "kite 2", "kite-2", "kite2"],
    "FLOKI": ["floki"],
    "Pieverse": ["pieverse"],
    "Ape and Pepe": ["ape and pepe", "ape-and-pepe", "apeandpepe", "apepe"],
    "Optimism": ["optimism"],
    "Conflux": ["cfx", "conflux", "conflux token", "conflux-token", "confluxtoken"],
    "Tezos": ["tezos", "xtz"],
    # TODO: add remark
    # "Ethereum Name Service": [
    #     "ens",
    #     "ethereum name service",
    #     "ethereum-name-service",
    #     "ethereumnameservice",
    # ],
    "Decred": ["dcr", "decred"],
    "Ribbita by Virtuals": [
        "ribbita by virtuals",
        "ribbita-by-virtuals",
        "ribbitabyvirtuals",
        "tibbir",
    ],
    "Maple Finance": ["maple finance", "maple-finance", "maplefinance", "syrup"],
    "Re Protocol reUSD": [
        "re protocol reusd",
        "re-protocol-reusd",
        "reprotocolreusd",
        "reusd",
    ],
    "Legacy Frax Dollar": [
        "frax",
        "legacy frax dollar",
        "legacy-frax-dollar",
        "legacyfraxdollar",
    ],
    "Grass": ["grass"],
    "JasmyCoin": ["jasmy", "jasmycoin"],
    "IOTA": ["iota"],
    "Compound": [
        "comp",
        "compound",
        "compound governance token",
        "compound-governance-token",
        "compoundgovernancetoken",
    ],
    "AUSD": ["agora dollar", "agora-dollar", "agoradollar", "ausd"],
    "Raydium": ["ray", "raydium"],
    "Kaia": ["kaia"],
    "EigenCloud (prev. EigenLayer)": [
        "eigen",
        "eigencloud prev eigenlayer",
        "eigencloud-prev-eigenlayer",
        "eigencloudpreveigenlayer",
        "eigenlayer",
    ],
    "Tradable NA Rent Financing Platform SSTN": [
        "pc0000031",
        "tradable na rent financing platform sstn",
        "tradable-na-rent-financing-platform-sstn",
        "tradablenarentfinancingplatformsstn",
    ],
    "Ultima": ["ultima"],
    "dogwifhat": ["dogwifcoin", "dogwifhat", "wif"],
    "Convex Finance": ["convex finance", "convex-finance", "convexfinance", "cvx"],
    "DoubleZero": ["doublezero"],
    "Theta Network": [
        "theta",
        "theta network",
        "theta token",
        "theta-network",
        "theta-token",
        "thetanetwork",
        "thetatoken",
    ],
    "Akedo": ["ake", "akedo"],
    "Starknet": ["starknet", "strk"],
    "Zebec Network": ["zbcn", "zebec network", "zebec-network", "zebecnetwork"],
    "Kinesis Silver": ["kag", "kinesis silver", "kinesis-silver", "kinesissilver"],
    "apyUSD": ["apyusd"],
    "The Graph": ["grt", "the graph", "the-graph", "thegraph"],
    "USAT": ["usa", "usat"],
    "Fartcoin": ["fartcoin"],
    "Trust Wallet": [
        "trust wallet",
        "trust wallet token",
        "trust-wallet",
        "trust-wallet-token",
        "trustwallet",
        "trustwallettoken",
        "twt",
    ],
    "KOGE": ["bnb48 club token", "bnb48-club-token", "bnb48clubtoken", "koge"],
    "Telcoin": ["tel", "telcoin"],
    "Axie Infinity": ["axie infinity", "axie-infinity", "axieinfinity", "axs"],
    "USDai": ["usdai"],
    "EUR CoinVertible": [
        "eur coinvertible",
        "eur-coinvertible",
        "eurcoinvertible",
        "eurcv",
        "societe generale forge eurcv",
        "societe-generale-forge-eurcv",
        "societegeneraleforgeeurcv",
    ],
    "coco": ["coco", "coco 2", "coco-2", "coco2"],
    "SwissBorg": ["borg", "swissborg"],
    "Akash Network": ["akash network", "akash-network", "akashnetwork", "akt"],
    "Tradable APAC Diversified Finance Provider SSTN": [
        "pc0000033",
        "tradable apac diversified finance provider sstn",
        "tradable-apac-diversified-finance-provider-sstn",
        "tradableapacdiversifiedfinanceprovidersstn",
    ],
    "OriginTrail": ["origintrail", "trac"],
    "THORChain": ["rune", "thorchain"],
    "Spiko US T-Bills Money Market Fund": [
        "spiko us t bills money market fund",
        "spiko-us-t-bills-money-market-fund",
        "spikoustbillsmoneymarketfund",
        "ustbl",
    ],
    "Strategy PP Variable xStock": [
        "strategy pp variable xstock",
        "strategy-pp-variable-xstock",
        "strategyppvariablexstock",
        "strcx",
    ],
    "Chiliz": ["chiliz", "chz"],
    "NEO": ["neo"],
    "MX": ["mx token", "mx-token", "mxtoken"],
    "GUSD": ["gusd"],
    "Onyxcoin": ["chain 2", "chain-2", "chain2", "onyxcoin", "xcn"],
    "Decentraland": ["decentraland", "mana"],
    "Spiko Amundi Overnight Swap Fund": [
        "safo",
        "spiko amundi overnight swap fund",
        "spiko-amundi-overnight-swap-fund",
        "spikoamundiovernightswapfund",
    ],
    "ApeCoin": ["ape", "apecoin"],
    "eCash": ["ecash", "xec"],
    "Arweave": ["arweave"],
    "Vision": ["vision", "vision 3", "vision-3", "vision3", "vsn"],
    "BUILDon": ["build on", "build-on", "buildon"],
    "BTSE Token": ["btse", "btse token", "btse-token", "btsetoken"],
    "SafePal": ["safepal", "sfp"],
    "edgeX": ["edge", "edgex"],
    "Tradable LatAm Fintech SSTN": [
        "pc0000097",
        "tradable latam fintech sstn",
        "tradable-latam-fintech-sstn",
        "tradablelatamfintechsstn",
    ],
    "The Sandbox": ["sand", "the sandbox", "the-sandbox", "thesandbox"],
    "Humanity": ["humanity"],
    "Synthetix": ["havven", "snx", "synthetix"],
    "Kamino": ["kamino", "kmno"],
    "Avant USD": ["avant usd", "avant-usd", "avantusd", "avusd"],
    "1INCH": ["1inch"],
    "GoMining Token": [
        "gmt token",
        "gmt-token",
        "gmttoken",
        "gomining",
        "gomining token",
        "gomining-token",
        "gominingtoken",
    ],
    "Railgun": ["rail", "railgun"],
    "Rollbit Coin": ["rlb", "rollbit coin", "rollbit-coin", "rollbitcoin"],
    "Shuffle": ["shfl", "shuffle", "shuffle 2", "shuffle-2", "shuffle2"],
    "Vaulta": ["vaulta"],
    "Meteora": ["met", "meteora"],
    "JPYSC": ["jpysc"],
    "AWE Network": [
        "awe",
        "awe network",
        "awe-network",
        "awenetwork",
        "stp network",
        "stp-network",
        "stpnetwork",
    ],
    "Ozone Chain": ["ozo", "ozone chain", "ozone-chain", "ozonechain"],
    "GRX Chain": ["grx", "grx chain", "grx-chain", "grxchain"],
    "Zano": ["zano"],
    "CASH": ["cash", "cash 4", "cash-4", "cash4"],
    "Zama": ["zama"],
    "Derive": ["derive", "drv"],
    "Theo Short Duration US Treasury Fund": [
        "thbill",
        "theo short duration us treasury fund",
        "theo-short-duration-us-treasury-fund",
        "theoshortdurationustreasuryfund",
    ],
    "The Black Bull": ["ansem", "the black bull", "the-black-bull", "theblackbull"],
    "Cash Cat": ["cash cat", "cash-cat", "cashcat"],
    "MetaDAO": ["meta", "meta 2 2", "meta-2-2", "meta22", "metadao"],
    "Circle Internet Group (Ondo Tokenized Stock)": [
        "circle internet group ondo tokenized stock",
        "circle-internet-group-ondo-tokenized-stock",
        "circleinternetgroupondotokenizedstock",
        "crclon",
    ],
    "Melania Meme": ["melania", "melania meme", "melania-meme", "melaniameme"],
    "Frax USD": ["frax usd", "frax-usd", "fraxusd", "frxusd"],
    "Tradable Singapore Fintech SSL": [
        "pc0000023",
        "tradable singapore fintech ssl",
        "tradable singapore fintech ssl 2",
        "tradable-singapore-fintech-ssl",
        "tradable-singapore-fintech-ssl-2",
        "tradablesingaporefintechssl",
        "tradablesingaporefintechssl2",
    ],
    "Aster USDF": [
        "aster usdf",
        "aster-usdf",
        "asterusdf",
        "astherus usdf",
        "astherus-usdf",
        "astherususdf",
    ],
    "Alpha Bulgaria Warrants": [
        "alfw",
        "alpha bulgaria warrants",
        "alpha-bulgaria-warrants",
        "alphabulgariawarrants",
    ],
    "Cheems Token": ["cheems", "cheems token", "cheems-token", "cheemstoken"],
    "Immutable": ["immutable", "immutable x", "immutable-x", "immutablex", "imx"],
    "Fluid": ["fluid", "instadapp"],
    "Backpack": ["backpack"],
    "Sonic": ["sonic", "sonic 3", "sonic-3", "sonic3"],
    "Golem": ["glm", "golem"],
    "Genius": ["genius", "genius 3", "genius-3", "genius3"],
    "SoSoValue": ["soso", "sosovalue"],
    "MultiversX": ["egld", "elrond erd 2", "elrond-erd-2", "elronderd2", "multiversx"],
    "Nexus Mutual": ["nexus mutual", "nexus-mutual", "nexusmutual", "nxm"],
    "Basic Attention": [
        "basic attention",
        "basic attention token",
        "basic-attention",
        "basic-attention-token",
        "basicattention",
        "basicattentiontoken",
        "bat",
    ],
    "Cap": ["cap", "cap 4", "cap-4", "cap4"],
    "Tradable NA Third Party Online Merchant SSTN": [
        "pc0000015",
        "tradable na third party online merchant sstn",
        "tradable-na-third-party-online-merchant-sstn",
        "tradablenathirdpartyonlinemerchantsstn",
    ],
    "dYdX": ["dydx", "dydx chain", "dydx-chain", "dydxchain"],
    "Horizen": ["horizen", "zen", "zencash"],
    "Four": ["form", "four"],
    "Chutes": ["chutes", "sn64"],
    "Securitize Tokenized AAA CLO Fund": [
        "securitize tokenized aaa clo fund",
        "securitize-tokenized-aaa-clo-fund",
        "securitizetokenizedaaaclofund",
        "stac",
    ],
    "Geodnet": ["geod", "geodnet"],
    "Unitas": ["unitas"],
    "Tradable LatAm Middle-Market Lender SSTL": [
        "pc0000085",
        "tradable latam middle market lender sstl",
        "tradable-latam-middle-market-lender-sstl",
        "tradablelatammiddlemarketlendersstl",
    ],
    "Tradable Singapore Fintech SSL (tradable-singapore-fintech-ssl)": ["pc0000077"],
    "Unity USD": ["unity usd", "unity-usd", "unityusd", "uusd"],
    "GALA": ["gala"],
    "Bermuda Shorts": ["bermuda shorts", "bermuda-shorts", "bermudashorts", "short"],
    "Sentient": ["sent", "sentient"],
    "WEMIX": ["wemix", "wemix token", "wemix-token", "wemixtoken"],
    "AB": ["newton project", "newton-project", "newtonproject"],
    "SAFEbit": ["safe", "safebit", "safecoin"],
    "Aethir": ["aethir", "ath"],
    "Apollo Diversified Credit Securitize Fund": [
        "acred",
        "apollo diversified credit securitize fund",
        "apollo-diversified-credit-securitize-fund",
        "apollodiversifiedcreditsecuritizefund",
    ],
    "Quack AI": ["quack ai", "quack-ai", "quackai"],
    "ZKsync": ["zksync"],
    "USDa": ["usda", "usda 2", "usda-2", "usda2"],
    "Saturn Dollar": ["saturn dollar", "saturn-dollar", "saturndollar", "usdat"],
    "TAGGER": ["tag", "tagger"],
    "Qtum": ["qtum"],
    "Goldfish Gold": ["ggbr", "goldfish gold", "goldfish-gold", "goldfishgold"],
    "Baby Claw": ["baby claw", "baby-claw", "babyclaw"],
    "Cysic": ["cys", "cysic"],
    "Banana For Scale": [
        "banana for scale",
        "banana for scale 2",
        "banana-for-scale",
        "banana-for-scale-2",
        "bananaforscale",
        "bananaforscale2",
        "bananas31",
    ],
    "deBridge": ["dbr", "debridge"],
    "Reserve Rights": [
        "reserve rights",
        "reserve rights token",
        "reserve-rights",
        "reserve-rights-token",
        "reserverights",
        "reserverightstoken",
        "rsr",
    ],
    "Pleasing Gold": ["pgold", "pleasing gold", "pleasing-gold", "pleasinggold"],
    "Cap USD": ["cap usd", "cap-usd", "capusd", "cusd"],
    "Nexus": ["nex", "nexus", "nexus 4", "nexus-4", "nexus4"],
    "YZY": ["yzy"],
    "DigiByte": ["dgb", "digibyte"],
    "MAG7.ssi": ["mag7 ssi", "mag7-ssi", "mag7ssi"],
    "Plume": ["plume"],
    "ORDI": ["ordi", "ordinals"],
    "RE": [],
    "0x Protocol": ["0x protocol", "0x-protocol", "0xprotocol", "zrx"],
    "Bending Spoons xStock": [
        "bending spoons xstock",
        "bending-spoons-xstock",
        "bendingspoonsxstock",
        "bspx",
    ],
    "USDA": ["usda 3", "usda-3", "usda3"],
    "KAITO": ["kaito"],
    "lium": ["celium", "lium", "sn51"],
    "yearn.finance": ["yearn finance", "yearn-finance", "yearnfinance", "yfi"],
    "BOOK OF MEME": ["bome", "book of meme", "book-of-meme", "bookofmeme"],
    "WrappedM by M0": ["wrappedm by m0", "wrappedm-by-m0", "wrappedmbym0"],
    "XPR Network": ["proton", "xpr", "xpr network", "xpr-network", "xprnetwork"],
    "Collector Crypt": [
        "cards",
        "collector crypt",
        "collector-crypt",
        "collectorcrypt",
    ],
    "Circle Internet Group (bStocks Tokenized Stock)": [
        "circle internet group bstock",
        "circle internet group bstocks tokenized stock",
        "circle-internet-group-bstock",
        "circle-internet-group-bstocks-tokenized-stock",
        "circleinternetgroupbstock",
        "circleinternetgroupbstockstokenizedstock",
        "crclb",
    ],
    "Rootstock Infrastructure Framework": [
        "rif",
        "rif token",
        "rif-token",
        "riftoken",
        "rootstock infrastructure framework",
        "rootstock-infrastructure-framework",
        "rootstockinfrastructureframework",
    ],
    "AntFun": ["antfun"],
    "Non-Playable Coin": [
        "non playable coin",
        "non-playable-coin",
        "nonplayablecoin",
        "npc",
    ],
    "Gas": ["gas"],
    "EXOD": ["exod"],
    "Beam": ["beam", "beam 2", "beam-2", "beam2"],
    "Arkham": ["arkham", "arkm"],
    "GMX": ["gmx"],
    "Orca": ["orca"],
    "STAU": ["stau"],
    # TODO
    # "Dog (Bitcoin)": [
    #     "dog",
    #     "dog bitcoin",
    #     "dog go to the moon rune",
    #     "dog-bitcoin",
    #     "dog-go-to-the-moon-rune",
    #     "dogbitcoin",
    #     "doggotothemoonrune",
    # ],
    "RaveDAO": ["rave", "ravedao"],
    "Tradable NA Post-Settlement Legal Financing Receivables": [
        "na post settlement legal financing receivables",
        "na-post-settlement-legal-financing-receivables",
        "napostsettlementlegalfinancingreceivables",
        "pc0000101",
        "tradable na post settlement legal financing receivables",
        "tradable-na-post-settlement-legal-financing-receivables",
        "tradablenapostsettlementlegalfinancingreceivables",
    ],
    "Bitget Wrapped BTC": [
        "bgbtc",
        "bitget wrapped btc",
        "bitget-wrapped-btc",
        "bitgetwrappedbtc",
    ],
    "Cygnus Finance Global USD": [
        "cgusd",
        "cygnus finance global usd",
        "cygnus-finance-global-usd",
        "cygnusfinanceglobalusd",
    ],
    "Tradable North America PoS Lender SSTN": [
        "pc0000019",
        "tradable north america pos lender sstn",
        "tradable-north-america-pos-lender-sstn",
        "tradablenorthamericaposlendersstn",
    ],
    "Lista USD": [
        "helio protocol hay",
        "helio-protocol-hay",
        "helioprotocolhay",
        "lista usd",
        "lista-usd",
        "listausd",
        "lisusd",
    ],
    "Tradable NA Neobank SSTL": [
        "tradable na neobank sstl",
        "tradable-na-neobank-sstl",
        "tradablenaneobanksstl",
    ],
    "USDsui": ["usdsui"],
    "Matrixdock Gold": ["matrixdock gold", "matrixdock-gold", "matrixdockgold", "xaum"],
    "Felix feUSD": ["felix feusd", "felix-feusd", "felixfeusd", "feusd"],
    "Anvil": ["anvil", "anvl"],
    "Mina Protocol": ["mina", "mina protocol", "mina-protocol", "minaprotocol"],
    "Targon": ["sn4", "targon"],
    "Crown BRLV": ["brlv", "crown brlv", "crown-brlv", "crownbrlv"],
    "Comedian": ["ban", "comedian"],
    "Useless Coin": [
        "useless",
        "useless 3",
        "useless coin",
        "useless-3",
        "useless-coin",
        "useless3",
        "uselesscoin",
    ],
    "SpaceX (bStocks Tokenized Stock)": [
        "spacex bstocks tokenized stock",
        "spacex-bstocks-tokenized-stock",
        "spacexbstockstokenizedstock",
        "spcxb",
    ],
    "Nest BlackOpal LiquidStone II Vault": [
        "nest blackopal liquidstone ii vault",
        "nest-blackopal-liquidstone-ii-vault",
        "nestblackopalliquidstoneiivault",
        "nopal",
    ],
    "Safe": [],
    "Purr": ["purr", "purr 2", "purr-2", "purr2"],
    "AIOZ Network": ["aioz", "aioz network", "aioz-network", "aioznetwork"],
    "Pearl": ["pearl", "pearl 2", "pearl-2", "pearl2", "prl"],
    "Midas mF-ONE": [
        "mf one",
        "mf-one",
        "mfone",
        "midas mf one",
        "midas-mf-one",
        "midasmfone",
    ],
    "o1.exchange": ["o1 exchange", "o1-exchange", "o1exchange"],
    "Kusama": ["ksm", "kusama"],
    "Ondo U.S. Dollar Token": [
        "ondo u s dollar token",
        "ondo-u-s-dollar-token",
        "ondousdollartoken",
        "usdon",
    ],
    "Livepeer": ["livepeer", "lpt"],
    "iShares Core S&P 500 ETF (Ondo Tokenized ETF)": [
        "ishares core s p 500 etf ondo tokenized etf",
        "ishares-core-s-p-500-etf-ondo-tokenized-etf",
        "isharescoresp500etfondotokenizedetf",
        "ivvon",
    ],
    "Tesla xStock": ["tesla xstock", "tesla-xstock", "teslaxstock", "tslax"],
    "Baby Doge Coin": ["baby doge coin", "baby-doge-coin", "babydoge", "babydogecoin"],
    "Circle xStock": ["circle xstock", "circle-xstock", "circlexstock", "crclx"],
    "Midas Fasanara Global": [
        "mglobal",
        "midas fasanara global",
        "midas-fasanara-global",
        "midasfasanaraglobal",
    ],
    "f(x) Protocol fxUSD": [
        "f x protocol fxusd",
        "f-x-protocol-fxusd",
        "fxprotocolfxusd",
        "fxusd",
    ],
    "AI Rig Complex": ["ai rig complex", "ai-rig-complex", "airigcomplex", "arc"],
    "CoW Protocol": ["cow", "cow protocol", "cow-protocol", "cowprotocol"],
    "GoPlus Security": ["goplus security", "goplus-security", "goplussecurity", "gps"],
    "Turbo": ["turbo"],
    "Bedrock": ["bedrock", "bedrock token", "bedrock-token", "bedrocktoken"],
    "UnifAI Network": ["uai", "unifai network", "unifai-network", "unifainetwork"],
    "Allora": ["allo", "allora"],
    "DeXe": ["dexe"],
    "Quantum Resistant Ledger": [
        "qrl",
        "quantum resistant ledger",
        "quantum-resistant-ledger",
        "quantumresistantledger",
    ],
    "Stronghold": [
        "shx",
        "stronghold",
        "stronghold token",
        "stronghold-token",
        "strongholdtoken",
    ],
    "Holo": ["holo", "holotoken", "hot"],
    "Swop": ["swop", "swop 2", "swop-2", "swop2"],
    "Midas mTBILL": ["midas mtbill", "midas-mtbill", "midasmtbill", "mtbill"],
    "Data Network": [
        "data",
        "data network",
        "data-network",
        "datanetwork",
        "story 2",
        "story-2",
        "story2",
    ],
    "MindWaveDAO": ["mindwavedao", "nila"],
    "SOON": ["soon", "soon 2", "soon-2", "soon2"],
    "Tori trUSD": ["tori trusd", "tori-trusd", "toritrusd", "trusd"],
    "Theta Fuel": ["tfuel", "theta fuel", "theta-fuel", "thetafuel"],
    "Velo": ["velo"],
    "SkyAI": ["skyai"],
    "Tradable Eu/LatAm PoS Financing SSTL": [
        "pc0000049",
        "tradable eu latam pos financing sstl",
        "tradable-eu-latam-pos-financing-sstl",
        "tradableeulatamposfinancingsstl",
    ],
    "Escoin": ["elg", "escoin", "escoin token", "escoin-token", "escointoken"],
    "SuperVerse": ["super", "superfarm", "superverse"],
    "Bio Protocol": ["bio", "bio protocol", "bio-protocol", "bioprotocol"],
    "Nexpace": ["nexpace", "nxpc"],
    "Diem": ["diem"],
    "ADI": ["adi", "adi token", "adi-token", "aditoken"],
    "f(x) USD Saving": [
        "f x usd saving",
        "f-x-usd-saving",
        "fx usd saving",
        "fx-usd-saving",
        "fxsave",
        "fxusdsaving",
    ],
    "Numeraire": ["nmr", "numeraire"],
    "CyberDEX": ["cyberdex", "cydx"],
    "TempleDAO": ["temple", "templedao"],
    "Hydration": ["hdx", "hydradx", "hydration"],
    "USD.AI": ["chip", "chip 2", "chip-2", "chip2", "usd ai", "usd-ai"],
    "would": ["would"],
    "Royal Euro": ["reur", "royal euro", "royal-euro", "royaleuro"],
    "StandX DUSD": ["dusd", "standx dusd", "standx-dusd", "standxdusd"],
    "DOLA": ["dola", "dola usd", "dola-usd", "dolausd"],
    "Spark": ["spark", "spark 2", "spark-2", "spark2", "spk"],
    "Wormhole": ["wormhole"],
    "Linea": ["linea"],
    "MEME HORSE": ["meme horse", "meme-horse", "memehorse", "mhorse"],
    "Sushi": ["sushi"],
    "Metal Blockchain": [
        "metal",
        "metal blockchain",
        "metal-blockchain",
        "metalblockchain",
    ],
    "Qubic": ["qubic", "qubic network", "qubic-network", "qubicnetwork"],
    "Wiki Cat": ["wiki cat", "wiki-cat", "wikicat", "wkc"],
    "Berachain": [
        "bera",
        "berachain",
        "berachain bera",
        "berachain-bera",
        "berachainbera",
    ],
    "ECOMI": ["ecomi", "omi"],
    "BNB Attestation Service": [
        "bas",
        "bnb attestation service",
        "bnb-attestation-service",
        "bnbattestationservice",
    ],
    "Espresso": ["esp", "espresso"],
    "Walrus": ["wal", "walrus", "walrus 2", "walrus-2", "walrus2"],
    "BasedHype": ["basedhype"],
    "Smilek to the Bank": [
        "smilek",
        "smilek to the bank",
        "smilek-to-the-bank",
        "smilektothebank",
    ],
    "VanEck Treasury Fund": [
        "vaneck treasury fund",
        "vaneck-treasury-fund",
        "vanecktreasuryfund",
        "vbill",
    ],
    "Talus": ["talus"],
    "ZIGChain": ["zig", "zigchain", "zignaly"],
    "Tradable NA Legal Receivables SSL": [
        "pc0000081",
        "tradable na legal receivables ssl",
        "tradable-na-legal-receivables-ssl",
        "tradablenalegalreceivablesssl",
    ],
    "MEMETOON": ["meme", "memetoon"],
    "LAB": ["lab"],
    "Ravencoin": ["ravencoin", "rvn"],
    "RedStone": [
        "red",
        "redstone",
        "redstone oracles",
        "redstone-oracles",
        "redstoneoracles",
    ],
    "Playnance": ["gcoin", "playnance"],
    "CROSS": ["cross", "cross 2", "cross-2", "cross2"],
    "Rekt": ["rekt", "rekt 4", "rekt-4", "rekt4"],
    "Jelly-My-Jelly": [
        "jelly my jelly",
        "jelly-my-jelly",
        "jellyjelly",
        "jellymyjelly",
    ],
    "Prize Protocol": ["prize", "prize protocol", "prize-protocol", "prizeprotocol"],
    "Brazilian Digital": [
        "brazilian digital",
        "brazilian-digital",
        "braziliandigital",
        "brz",
    ],
    "JPY Coin": ["jpy coin", "jpy-coin", "jpyc", "jpycoin"],
    "Seeker": ["seeker", "skr"],
    "FUNToken": ["fun", "funfair", "funtoken"],
    "Flying Tulip": ["flying tulip", "flying-tulip", "flyingtulip"],
    "ChainOpera AI": ["chainopera ai", "chainopera-ai", "chainoperaai", "coai"],
    "Tutorial": ["tut", "tutorial"],
    "Popcat": ["popcat"],
    "AllUnity CHF": ["allunity chf", "allunity-chf", "allunitychf", "chfau"],
    "Enjin Coin": ["enj", "enjin coin", "enjin-coin", "enjincoin"],
    "Nano": ["nano", "xno"],
    "io.net": ["io net", "io-net", "ionet"],
    "Zilliqa": ["zil", "zilliqa"],
    "Capricorn": ["apr", "apriori", "capricorn"],
    "Prom": ["prom", "prometeus"],
    "Pharos": ["pharos", "pharos network", "pharos-network", "pharosnetwork", "pros"],
    "MicroStrategy xStock": [
        "microstrategy xstock",
        "microstrategy-xstock",
        "microstrategyxstock",
        "mstrx",
    ],
    "APES": ["apes", "apes 2 2", "apes-2-2", "apes22"],
    "FONQ": ["fonq"],
    "ConstitutionDAO": ["constitutiondao", "people"],
    "Babylon": ["baby", "babylon"],
    "Venus": ["venus", "xvs"],
    "Neutrl USD": [
        "neutrl usd",
        "neutrl-usd",
        "neutrlusd",
        "nusd",
        "nusd 2",
        "nusd-2",
        "nusd2",
    ],
    "Tellor Tributes": [
        "tellor",
        "tellor tributes",
        "tellor-tributes",
        "tellortributes",
        "trb",
    ],
    "Peanut the Squirrel": [
        "peanut the squirrel",
        "peanut-the-squirrel",
        "peanutthesquirrel",
        "pnut",
    ],
    "Brett": ["based brett", "based-brett", "basedbrett", "brett"],
    "aelf": ["aelf", "elf"],
    "Centrifuge": ["centrifuge", "centrifuge 2", "centrifuge-2", "centrifuge2", "cfg"],
    "UnityWallet Token": [
        "unitywallet token",
        "unitywallet-token",
        "unitywallettoken",
        "unt",
    ],
    "SP500 xStock": ["sp500 xstock", "sp500-xstock", "sp500xstock", "spyx"],
    "Precious Metals USD": [
        "pmusd",
        "precious metals usd",
        "precious-metals-usd",
        "preciousmetalsusd",
    ],
    "USDu": ["usdu"],
    "Toshi": ["toshi"],
    "Billions Network": [
        "bill",
        "billions network",
        "billions-network",
        "billionsnetwork",
    ],
    "TROLL": ["troll", "troll 2", "troll-2", "troll2"],
    "Flow": ["flow"],
    "Axelar": ["axelar", "axl"],
    "ZetaChain": ["zeta", "zetachain"],
    "Holoworld": ["holoworld"],
    "iShares Bitcoin Trust (Ondo Tokenized)": [
        "ibiton",
        "ishares bitcoin trust ondo tokenized",
        "ishares-bitcoin-trust-ondo-tokenized",
        "isharesbitcointrustondotokenized",
    ],
    "Anemoy Tokenized Apollo Diversified Credit Fund": [
        "acrdx",
        "anemoy tokenized apollo diversified credit fund",
        "anemoy-tokenized-apollo-diversified-credit-fund",
        "anemoytokenizedapollodiversifiedcreditfund",
    ],
    "Nockchain": ["nock", "nockchain"],
    "Fidelity Digital Interest Token": [
        "fdit",
        "fidelity digital interest token",
        "fidelity-digital-interest-token",
        "fidelitydigitalinteresttoken",
    ],
    "Ozapay": ["oza", "ozapay"],
    "NA Capital-as-a-Service SSTN": [
        "na capital as a service sstn",
        "na-capital-as-a-service-sstn",
        "nacapitalasaservicesstn",
        "pc0016245",
    ],
    "Oasis": ["oasis", "oasis network", "oasis-network", "oasisnetwork", "rose"],
    "Score": ["score", "sn44"],
    "AI XOVIA": ["ai xovia", "ai-xovia", "aix", "aixovia"],
    "BlackRock Daily Reinvestment Stablecoin Reserve Vehicle": [
        "blackrock daily reinvestment stablecoin reserve vehicle",
        "blackrock-daily-reinvestment-stablecoin-reserve-vehicle",
        "blackrockdailyreinvestmentstablecoinreservevehicle",
        "brsrv",
    ],
    "Alloy Tether": ["alloy tether", "alloy-tether", "alloytether", "ausdt"],
    "USDKG": ["usdkg"],
    "Creditcoin": ["creditcoin", "creditcoin 2", "creditcoin-2", "creditcoin2", "ctc"],
    "Fidelity Digital Dollar": [
        "fidd",
        "fidelity digital dollar",
        "fidelity-digital-dollar",
        "fidelitydigitaldollar",
    ],
    "Kava": ["kava"],
    "MegaETH": ["mega", "megaeth"],
    "Concordium": ["ccd", "concordium"],
    "Nervos Network": ["ckb", "nervos network", "nervos-network", "nervosnetwork"],
    "Ontology": ["ont", "ontology"],
    "Kinetiq": ["kinetiq", "kntq"],
    "JupUSD": ["jupusd"],
    "affine": ["affine", "sn120"],
    "InfiniFi USD": ["infinifi usd", "infinifi-usd", "infinifiusd", "iusd"],
    "peaq": ["peaq", "peaq 2", "peaq-2", "peaq2"],
    "Sygnum FIUSD Liquidity Fund": [
        "fiusd",
        "sygnum fiusd liquidity fund",
        "sygnum-fiusd-liquidity-fund",
        "sygnumfiusdliquidityfund",
    ],
    "bitcastle Token": ["bce", "bitcastle token", "bitcastle-token", "bitcastletoken"],
    "Mantis": ["mantis"],
    "Xphere": ["xphere"],
    "Astar": ["astar", "astr"],
    "BIM": ["bim", "bim 2", "bim-2", "bim2"],
    "Polymesh": ["polymesh", "polyx"],
    "Blur": ["blur"],
    "ETHGas": ["ethgas", "ethgas 2", "ethgas-2", "ethgas2", "gwei"],
    "Tradable LatAm BNPL SSTN": [
        "pc0000027",
        "tradable latam bnpl sstn",
        "tradable-latam-bnpl-sstn",
        "tradablelatambnplsstn",
    ],
    "Keeta": ["keeta", "kta"],
    "Loaded Lions": ["lion", "loaded lions", "loaded-lions", "loadedlions"],
    "Celo": ["celo"],
    "牛来 (Niu Lai)": ["niu lai", "niu-lai", "niulai"],
    "Mog Coin": ["mog", "mog coin", "mog-coin", "mogcoin"],
    "Pentagon Chain": ["pentagon chain", "pentagon-chain", "pentagonchain"],
    "River": ["river"],
    "DAPPOS": ["dappos", "dos"],
    "DUSK": ["dusk", "dusk network", "dusk-network", "dusknetwork"],
    "XYO Network": ["xyo", "xyo network", "xyo-network", "xyonetwork"],
    "Fidelity USD Digital Liquidity Fund-Acc": [
        "fidelity usd digital liquidity fund acc",
        "fidelity-usd-digital-liquidity-fund-acc",
        "fidelityusddigitalliquidityfundacc",
        "filq a",
        "filq-a",
        "filqa",
    ],
    "Micron Technology (bStocks Tokenized Stock)": [
        "micron technology bstock",
        "micron technology bstocks tokenized stock",
        "micron-technology-bstock",
        "micron-technology-bstocks-tokenized-stock",
        "microntechnologybstock",
        "microntechnologybstockstokenizedstock",
        "mub",
    ],
    "SPDR S&P 500 ETF (Ondo Tokenized ETF)": [
        "spdr s p 500 etf ondo tokenized etf",
        "spdr-s-p-500-etf-ondo-tokenized-etf",
        "spdrsp500etfondotokenizedetf",
        "spyon",
    ],
    "Magma Finance": ["magma", "magma finance", "magma-finance", "magmafinance"],
}
